os: linux
sudo: true
language: android
android:
  components:
    - build-tools-27.0.3
    - android-26

before_script:
  - sudo apt-get install ant
  - git clone https://github.com/facebook/buck.git --branch master --depth=1 $HOME/buck
  - cd $HOME/buck && ant
  - $HOME/buck/bin/buck --version

script:
  - $HOME/buck/bin/buck fetch //...
  - $HOME/buck/bin/buck build :soloader
